### use balance-1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 30000
}

### use balance-2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 30000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "45d498714fca40c58c218ebd761ae9a2",
  "accountNumber": "1000000002",
  "amount": 30000
}

### query transaction
GET http://localhost:8080/transaction/ef35a47d677242739f45eecb4c321063